name: Linux Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  basic-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release
