name: CI

on:
  push:
  pull_request:
    branches:
      - "main"

jobs:
  basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: choco install llvm

      - name: Check clang-format version
        run: clang-format --version

      - name: Clang format check
        run: |
          find . -name '*.cpp' -or -name '*.h' | xargs clang-format -i --style=file
          git diff --exit-code

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release

  basic-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 16

      - name: Check clang-format version
        run: clang-format --version

      - name: Clang format check
        run: |
          find . -name '*.cpp' -or -name '*.h' | xargs clang-format-16 -i --style=file
          git diff

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release
