name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install llvm --version 12.0.0
            echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH
          else
            sudo apt-get install -y clang-format
          fi

      - name: Clang format check
        run: |
          find . -name '*.cpp' -or -name '*.h' | xargs clang-format -i --style=file
          git diff --exit-code

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release
